### ISSUE TITLE
テストデータ用意のためシードデータを用意する

### ISSUE THREAD

**Issue by norotime** [m-tsukada/story-sotsugyoukadai#11]
https://github.com/m-tsukada/story-sotsugyoukadai/blob/master/db/seeds.rb

@m-tsukada こちらも追加でお願いします。環境構築のつど、て入力するのは大変です。

**Comment by m-tsukada** [comment]
ユーザの登録はseed.rbに記載しています。ですが、ログイン情報が必要な他のデータの投入方法ができずにこまっております。

**Comment by m-tsukada** [comment]
上記の他のデータの投入もできましたので、githubにpushしました。
