### ISSUE TITLE
ヘルパーメソッドと同一であれば削除する

### ISSUE THREAD

**Issue by norotime** [m-tsukada/story-sotsugyoukadai#3]
https://github.com/m-tsukada/story-sotsugyoukadai/blob/f8b133f52e9ccbddc87c8104e897cfea2fbafb36/app/controllers/blogs_controller.rb#L70

**Comment by m-tsukada** [comment]
logged_in?メソッドではうまくいかなかったので、新しいメソッドをblogs_controllerにも作成したのですが、いま確認すると問題ないので、not_current_userを削除しました。

**Comment by norotime** [comment]
@m-tsukada はい〜。
