### ISSUE TITLE
アソシエーションメソッドを使い一行で記載する

### ISSUE THREAD

**Issue by norotime** [m-tsukada/story-sotsugyoukadai#4]
https://github.com/m-tsukada/story-sotsugyoukadai/blob/f8b133f52e9ccbddc87c8104e897cfea2fbafb36/app/controllers/comments_controller.rb#L8

buildを使って一行で記載してください。

**Comment by m-tsukada** [comment]
@comment = current_user.comments.build(comment_params)と修正しました。
