### ISSUE TITLE
カラム名を再検討する

### ISSUE THREAD

**Issue by norotime** [m-tsukada/story-sotsugyoukadai#9]
https://github.com/m-tsukada/story-sotsugyoukadai/blob/f8b133f52e9ccbddc87c8104e897cfea2fbafb36/db/migrate/20180331130210_create_comments.rb#L6

@m-tsukada コメントテーブルのコメントカラム、間違えやすいため、contentなどにしませんか？

**Comment by m-tsukada** [comment]
承知しました。
rails generate migration rename_comment_column_to_comments
でmigrationファイルを作成、rake db:migrateし、commentカラムを使用していたviewを修正しました。
